import { Customer, Deal, Product, Quotation, Activity } from './types';

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust_1',
    name: 'คุณสมชาย วิจิตรศิลป์',
    company: 'บริษัท สยาม โกลบอล เทคโนโลยี จำกัด',
    email: 'somchai@siamglobaltech.co.th',
    phone: '081-456-7890',
    address: '888 อาคารไซเบอร์เวิลด์ ทาวเวอร์ ชั้น 24 ถ.รัชดาภิเษก ห้วยขวาง กรุงเทพฯ 10310',
    taxId: '0105560123456',
    tags: ['Corporate', 'Enterprise', 'VIP'],
    type: 'company',
    createdAt: '2026-08-15T09:00:00Z',
    avatarColor: 'bg-blue-600',
  },
  {
    id: 'cust_2',
    name: 'คุณณิชา พงษ์ไพศาล',
    company: 'บจก. บางกอก ดีไซน์ สตูดิโอ',
    email: 'nicha@bangkokdesign.com',
    phone: '089-123-4567',
    address: '45/12 ซอยสุขุมวิท 39 แขวงคลองตันเหนือ เขตวัฒนา กรุงเทพฯ 10110',
    taxId: '0105559876543',
    tags: ['SME', 'Creative', 'Design'],
    type: 'company',
    createdAt: '2026-08-20T14:30:00Z',
    avatarColor: 'bg-purple-600',
  },
  {
    id: 'cust_3',
    name: 'คุณธนภัทร รัตนมนตรี',
    company: 'ห้างหุ้นส่วนจำกัด ธนภัทร โลจิสติกส์',
    email: 'thanapat@tptransport.net',
    phone: '062-888-9900',
    address: '109/4 หมู่ 5 ถ.บางนา-ตราด กม.18 อ.บางพลี จ.สมุทรปราการ 10540',
    taxId: '0113562001122',
    tags: ['Logistics', 'Fleet', 'High Priority'],
    type: 'company',
    createdAt: '2026-08-25T11:15:00Z',
    avatarColor: 'bg-emerald-600',
  },
  {
    id: 'cust_4',
    name: 'คุณกิตติศักดิ์ พรหมรักษา',
    company: 'คลินิกทันตกรรมสไมล์เซ็นเตอร์',
    email: 'kittisak.smile@gmail.com',
    phone: '095-777-3344',
    address: '12/88 ถ.พหลโยธิน แขวงลาดยาว เขตจตุจักร กรุงเทพฯ 10900',
    taxId: '0105563045678',
    tags: ['Healthcare', 'Clinic'],
    type: 'company',
    createdAt: '2026-09-01T10:00:00Z',
    avatarColor: 'bg-cyan-600',
  },
  {
    id: 'cust_5',
    name: 'คุณแพรวพรรณ เลิศวิริยะ',
    company: '',
    email: 'praewpan.l@gmail.com',
    phone: '086-333-2211',
    address: '99/55 หมู่บ้านลัดดารมย์ ถ.ราชพฤกษ์ ต.บางกร่าง อ.เมือง จ.นนทบุรี 11000',
    tags: ['Individual', 'Retail'],
    type: 'individual',
    createdAt: '2026-09-03T16:20:00Z',
    avatarColor: 'bg-rose-600',
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    code: 'SOFT-001',
    name: 'แพ็กเกจระบบ CRM & Sales Pro (รายปี)',
    description: 'ระบบบริหารงานขายและทีมเซลส์ พร้อมแดชบอร์ดและการออกใบเสนอราคา',
    price: 39000,
    cost: 12000,
    unit: 'ปี',
    category: 'Software & Cloud',
    stock: 999,
  },
  {
    id: 'prod_2',
    code: 'SRV-001',
    name: 'บริการ Setup & Onboarding ระบบ (พร้อมอบรมทีม)',
    description: 'ติดตั้งระบบ ตั้งค่าตาม Workflow องค์กร พร้อมจัดอบรมทีมงาน 1 วันเต็ม',
    price: 15000,
    cost: 5000,
    unit: 'ครั้ง',
    category: 'Service',
    stock: 999,
  },
  {
    id: 'prod_3',
    code: 'SRV-002',
    name: 'บริการ Customization & Integration API',
    description: 'เชื่อมต่อ API กับระบบ ERP หรือ Line OA ตามความต้องการเฉพาะ',
    price: 25000,
    cost: 10000,
    unit: 'ระบบ',
    category: 'Service',
    stock: 999,
  },
  {
    id: 'prod_4',
    code: 'HW-001',
    name: 'เครื่องสแกนบาร์โค้ดไร้สาย Industrial Grade',
    description: 'หัวอ่าน 2D ความเร็วสูง แบตเตอรี่อึด ทนทานตกกระแทก 1.5 เมตร',
    price: 4900,
    cost: 2900,
    unit: 'เครื่อง',
    category: 'Hardware',
    stock: 45,
  },
  {
    id: 'prod_5',
    code: 'HW-002',
    name: 'เครื่องพิมพ์ใบเสร็จ/ใบส่งของความร้อน 80mm Wi-Fi',
    description: 'พิมพ์เร็ว คมชัด ตัดกระดาษอัตโนมัติ รองรับภาษาไทยสมบูรณ์',
    price: 3500,
    cost: 2100,
    unit: 'เครื่อง',
    category: 'Hardware',
    stock: 28,
  }
];

export const INITIAL_DEALS: Deal[] = [
  {
    id: 'deal_1',
    title: 'โครงการติดตั้งระบบ CRM ประจำปี 2026',
    customerId: 'cust_1',
    value: 79000,
    stage: 'negotiation',
    probability: 80,
    expectedCloseDate: '2026-09-18',
    assignedTo: 'อัครชัย (เซลส์มาสเตอร์)',
    notes: 'ลูกค้าต้องการส่วนลดแพ็กเกจ 2 ปี อยู่ระหว่างเสนอผู้บริหาร',
    createdAt: '2026-08-16T10:00:00Z',
    updatedAt: '2026-09-05T14:20:00Z',
  },
  {
    id: 'deal_2',
    title: 'แพ็กเกจ Cloud Solution และอุปกรณ์ POS',
    customerId: 'cust_2',
    value: 47400,
    stage: 'proposal_sent',
    probability: 60,
    expectedCloseDate: '2026-09-25',
    assignedTo: 'อัครชัย (เซลส์มาสเตอร์)',
    notes: 'ส่งใบเสนอราคา QT-2609-0001 เรียบร้อยแล้ว นัดโทรคุยวันพฤหัส',
    createdAt: '2026-08-22T15:00:00Z',
    updatedAt: '2026-09-04T11:00:00Z',
  },
  {
    id: 'deal_3',
    title: 'ระบบจัดการ Fleet และ Hardware สแกนเนอร์ 10 ชุด',
    customerId: 'cust_3',
    value: 125000,
    stage: 'contacted',
    probability: 40,
    expectedCloseDate: '2026-10-10',
    assignedTo: 'อัครชัย (เซลส์มาสเตอร์)',
    notes: 'นัด Demo ระบบให้ฝ่ายปฏิบัติการดูในสัปดาห์หน้า',
    createdAt: '2026-08-26T09:30:00Z',
    updatedAt: '2026-09-06T16:00:00Z',
  },
  {
    id: 'deal_4',
    title: 'ระบบนัดหมายคนไข้และบริหารเวชระเบียน',
    customerId: 'cust_4',
    value: 54000,
    stage: 'closed_won',
    probability: 100,
    expectedCloseDate: '2026-09-02',
    assignedTo: 'อัครชัย (เซลส์มาสเตอร์)',
    notes: 'ลูกค้าเซ็นสัญญาและชำระมัดจำงวดแรกเรียบร้อย เริ่ม Onboarding วันที่ 15',
    createdAt: '2026-08-10T11:00:00Z',
    updatedAt: '2026-09-02T17:30:00Z',
  },
  {
    id: 'deal_5',
    title: 'สอบถามโปรแกรมจัดการหน้าร้าน',
    customerId: 'cust_5',
    value: 18500,
    stage: 'lead_in',
    probability: 20,
    expectedCloseDate: '2026-09-30',
    assignedTo: 'อัครชัย (เซลส์มาสเตอร์)',
    notes: 'ทักมาจากหน้าเพจ Facebook สนใจเริ่มใช้เดือนหน้า',
    createdAt: '2026-09-03T16:30:00Z',
    updatedAt: '2026-09-03T16:30:00Z',
  }
];

export const INITIAL_QUOTATIONS: Quotation[] = [
  {
    id: 'qt_1',
    quotationNumber: 'QT-2609-0001',
    date: '2026-09-04',
    validUntil: '2026-10-04',
    customerId: 'cust_2',
    customerName: 'คุณณิชา พงษ์ไพศาล',
    customerCompany: 'บจก. บางกอก ดีไซน์ สตูดิโอ',
    customerAddress: '45/12 ซอยสุขุมวิท 39 แขวงคลองตันเหนือ เขตวัฒนา กรุงเทพฯ 10110',
    customerTaxId: '0105559876543',
    customerPhone: '089-123-4567',
    customerEmail: 'nicha@bangkokdesign.com',
    dealId: 'deal_2',
    items: [
      {
        id: 'qti_1',
        productId: 'prod_1',
        name: 'แพ็กเกจระบบ CRM & Sales Pro (รายปี)',
        description: 'รวมฟังก์ชันจัดการการขายและรายงานครบวงจร',
        quantity: 1,
        unit: 'ปี',
        unitPrice: 39000,
        discount: 0,
        amount: 39000,
      },
      {
        id: 'qti_2',
        productId: 'prod_5',
        name: 'เครื่องพิมพ์ใบเสร็จ/ใบส่งของความร้อน 80mm Wi-Fi',
        description: 'รับประกัน 1 ปีเต็ม',
        quantity: 2,
        unit: 'เครื่อง',
        unitPrice: 3500,
        discount: 500,
        amount: 6500,
      }
    ],
    subtotal: 45500,
    discountTotal: 500,
    vatRate: 7,
    vatAmount: 3185,
    grandTotal: 48685,
    status: 'sent',
    notes: 'ใบเสนอราคามีผล 30 วันนับจากวันที่ออกเอกสาร',
    terms: '1. มัดจำ 50% เมื่องวดแรก\n2. ชำระส่วนที่เหลือ 50% ภายใน 15 วันหลังส่งมอบงาน',
    salesPerson: 'อัครชัย (ฝ่ายขาย)',
    createdAt: '2026-09-04T10:00:00Z',
  }
];

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: 'act_1',
    type: 'call',
    title: 'โทรติดตามผลใบเสนอราคา QT-2609-0001',
    description: 'โทรสอบถามคุณณิชา เกี่ยวกับข้อเสนอแพ็กเกจ CRM และเครื่องพิมพ์',
    customerId: 'cust_2',
    dealId: 'deal_2',
    dueDate: '2026-09-08',
    completed: false,
    priority: 'high',
    createdAt: '2026-09-04T11:30:00Z',
  },
  {
    id: 'act_2',
    type: 'meeting',
    title: 'ประชุมสรุปขอบเขตงาน Custom Integration',
    description: 'ประชุมทาง Zoom กับทีมไอที บ. สยาม โกลบอล เทคโนโลยี',
    customerId: 'cust_1',
    dealId: 'deal_1',
    dueDate: '2026-09-09',
    completed: false,
    priority: 'high',
    createdAt: '2026-09-05T14:00:00Z',
  },
  {
    id: 'act_3',
    type: 'task',
    title: 'เตรียมเอกสารสัญญาและจัดส่ง Onboarding Pack',
    description: 'ส่งเอกสารให้คลินิกทันตกรรมสไมล์เซ็นเตอร์',
    customerId: 'cust_4',
    dealId: 'deal_4',
    dueDate: '2026-09-10',
    completed: false,
    priority: 'medium',
    createdAt: '2026-09-02T18:00:00Z',
  },
  {
    id: 'act_4',
    type: 'email',
    title: 'ส่งโบรชัวร์และตัวอย่างให้คุณแพรวพรรณ',
    description: 'ส่งแคตตาล็อกสินค้าและวิดีโอแนะนำทาง Email',
    customerId: 'cust_5',
    dealId: 'deal_5',
    dueDate: '2026-09-07',
    completed: true,
    priority: 'low',
    createdAt: '2026-09-03T17:00:00Z',
  }
];
